# Generated by Django 3.2.15 on 2022-08-22 11:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('krs_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('city', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('street_number', models.CharField(blank=True, max_length=100)),
                ('phone_numer', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200)),
                ('production_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RobotManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('hq_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RobotModificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RobotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_type', models.CharField(choices=[('4wheeler', '4 wheeler'), ('amphibian', 'amphibian'), ('tracked', 'tracked'), ('flying', 'flying')], default='default', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('robot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robots.robot')),
            ],
        ),
        migrations.AddField(
            model_name='robot',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='robots.robotmanufacturer'),
        ),
        migrations.AddField(
            model_name='robot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.client'),
        ),
        migrations.AddField(
            model_name='robot',
            name='proprietor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='robot',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='robots.robottype'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('robot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robots.robot')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('x_size', models.FloatField()),
                ('y_size', models.FloatField()),
                ('z_size', models.FloatField()),
                ('robot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_device', to='robots.robot')),
            ],
        ),
    ]
