# Generated by Django 4.0.4 on 2022-07-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_type', models.CharField(choices=[('4W', '4 wheeler'), ('AM', 'Amphibian'), ('TR', 'Tracked'), ('FL', 'Flying')], default='none', max_length=20)),
            ],
        ),
    ]
