# Generated by Django 3.2.15 on 2022-08-22 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_client_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotmodificationhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 16, 56, 21, 522188)),
            preserve_default=False,
        ),
    ]
