# Generated by Django 3.2.15 on 2022-08-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_robotmodificationhistory_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robotmodificationhistory',
            old_name='date',
            new_name='modification_date',
        ),
    ]
