# Generated by Django 3.2.14 on 2022-07-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0005_client_robotmanufacturer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RobotManufacturer",
        ),
    ]
