# Generated by Django 3.2.14 on 2022-07-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0006_delete_robotmanufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country_of_origin', models.CharField(max_length=20)),
                ('HQ_location', models.CharField(max_length=20)),
                ('robot_types', models.CharField(choices=[('4WEELER', '4 wheeler'), ('AMPHIBIAN', 'Amphibian'), ('TRACKED', 'Tracked'), ('FLYING', 'Flying')], max_length=20)),
            ],
        ),
    ]
