# Generated by Django 3.2.14 on 2022-07-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0007_robotmanufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='robot_owner',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
