# Generated by Django 3.2.14 on 2022-07-14 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0008_robot_robot_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="robot_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="robots.client"
            ),
        ),
    ]
