# Generated by Django 3.2.14 on 2022-07-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0009_alter_robot_robot_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communicationdevice',
            old_name='device_id',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='communicationdevice',
            old_name='device_x_size',
            new_name='x_size',
        ),
        migrations.RenameField(
            model_name='communicationdevice',
            old_name='device_y_size',
            new_name='y_size',
        ),
        migrations.RenameField(
            model_name='communicationdevice',
            old_name='device_z_size',
            new_name='z_size',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='communication_device_id',
            new_name='communication_device_name',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='communication_device_id',
            new_name='communication_device_name',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='robot_manufacturer',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='robot_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='robot_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='robot_production_date',
            new_name='production_date',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='robot_serial_number',
            new_name='serial_number',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='robot_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='telemetry',
            old_name='communication_device_id',
            new_name='communication_device_name',
        ),
    ]
