# Generated by Django 3.2.14 on 2022-07-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0010_auto_20220714_2136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="robots.robotmanufacturer",
            ),
        ),
    ]
