# Generated by Django 3.2.14 on 2022-07-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0012_auto_20220716_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotmanufacturer',
            name='robot_types',
        ),
    ]
