# Generated by Django 3.2.14 on 2022-07-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0013_remove_robotmanufacturer_robot_types"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="communication_device_name",
            new_name="communication_device",
        ),
        migrations.RenameField(
            model_name="robot",
            old_name="communication_device_name",
            new_name="communication_device",
        ),
        migrations.RenameField(
            model_name="telemetry",
            old_name="communication_device_name",
            new_name="communication_device",
        ),
        migrations.RemoveField(
            model_name="robotmanufacturer",
            name="HQ_location",
        ),
        migrations.AddField(
            model_name="client",
            name="City",
            field=models.CharField(default="city", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="Phone_numer",
            field=models.CharField(default="number", max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="Street",
            field=models.CharField(default="street", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="Street_number",
            field=models.CharField(default="number", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="robotmanufacturer",
            name="hq_location",
            field=models.CharField(default="hq", max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="communicationdevice",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="robot",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="robot",
            name="serial_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="robotmanufacturer",
            name="country_of_origin",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="robotmanufacturer",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
