# Generated by Django 3.2.14 on 2022-07-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0015_alter_robottype_robot_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='robot_object',
        ),
        migrations.RemoveField(
            model_name='telemetry',
            name='robot_object',
        ),
    ]
