# Generated by Django 3.2.14 on 2022-08-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0018_auto_20220801_1313"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communicationdevice",
            name="is_faulty",
        ),
        migrations.AlterField(
            model_name="client",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone_numer",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="client",
            name="street",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="street_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="communicationdevice",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="robot",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="robot",
            name="serial_number",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="robotmanufacturer",
            name="country_of_origin",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="robotmanufacturer",
            name="hq_location",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="robotmanufacturer",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="robottype",
            name="robot_type",
            field=models.CharField(
                choices=[
                    ("4wheeler", "4 wheeler"),
                    ("amphibian", "amphibian"),
                    ("tracked", "tracked"),
                    ("flying", "flying"),
                ],
                default="default",
                max_length=20,
            ),
        ),
    ]
