# Generated by Django 3.2.14 on 2022-08-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0019_auto_20220801_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='communication_device',
        ),
        migrations.RemoveField(
            model_name='telemetry',
            name='communication_device',
        ),
        migrations.AddField(
            model_name='location',
            name='robot_name',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='robots.robot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telemetry',
            name='robot_name',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='robots.robot'),
            preserve_default=False,
        ),
    ]
