# Generated by Django 3.2.14 on 2022-08-02 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0020_auto_20220801_1431"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="robot",
            name="communication_device",
        ),
        migrations.AddField(
            model_name="communicationdevice",
            name="robot",
            field=models.OneToOneField(
                default=2,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="communication_device",
                to="robots.robot",
            ),
            preserve_default=False,
        ),
    ]
