# Generated by Django 3.2.15 on 2022-08-05 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0023_alter_communicationdevice_robot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationdevice',
            name='robot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='communication_device', to='robots.robot'),
        ),
    ]
