# Generated by Django 3.2.15 on 2022-08-06 14:50

import robots.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0024_alter_communicationdevice_robot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="krs_number",
            field=models.IntegerField(
                validators=[robots.validators.validate_krs]
            ),
        ),
    ]
