# Generated by Django 3.2.15 on 2022-08-08 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0025_alter_client_krs_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communicationdevice",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="communicationdevice",
            name="robot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="communication_device",
                to="robots.robot",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="robot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="robots.robot",
            ),
        ),
        migrations.AlterField(
            model_name="telemetry",
            name="robot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="robots.robot",
            ),
        ),
    ]
