# Generated by Django 3.2.15 on 2022-08-09 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0028_auto_20220808_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='krs_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='robotmodificationhistory',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='robotmodificationhistory',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='robotmodificationhistory',
            name='owner',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='robotmodificationhistory',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robotmodificationhistory',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='robotmodificationhistory',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
