# Generated by Django 3.2.15 on 2022-08-10 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robots', '0030_robot_proprietor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='proprietor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
