version: "3.9"
   
services:

  backend:
    build: ./backend
    image: backend-image
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database
      - redis

  database:
    image: postgres
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports: 
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  
  # celery:
  #   build: ./backend
  #   container_name: celery
  #   command: sh -c 'celery -A pinewatchers worker -l info'
  #   volumes:
  #     - ./backend:/code
  #   env_file:
  #     - .env
  #   depends_on:
  #     - backend
  #     - redis
  
  # consumer:
  #   image: backend-image
  #   container_name: consumer
  #   command: python3 consumer.py
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis

volumes:
  postgres_data:
  cache:
