version: "3.9"
   
services:

  backend:
    build: ./backend
    image: backend-image
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  
  consumer:
    image: backend-image
    container_name: consumer
    command: python3 consumer.py

volumes:
  postgres_data:
